apiVersion: argoprj.io/v1alpha1
kind: Application
metadata:
  name: devops-project
  namespace: argocd
spec:
  project: default
  source: 
    repoURL : "https://github.com/bigstan00/devops-project"
    targetRevision: HEAD
    path: devops-project-time-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace:default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

      