name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t bigstan00/devops-project:${{ env.SHORT_SHA }} .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: |
          docker push bigstan00/devops-project:${{ env.SHORT_SHA }}
      
      - name: configure git author
        run: |
          git config --local user.email "sdakwoji@gmail.com"
          git config --local user.name "bigstan00"


      - name: Update Helm chart with new imagge tag
        run: |
         sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./devops-project-time-app/values.yaml
         git add . /devops-project-time-app/values.yaml
         git commit -m "updated image tag to ${{ env.SHORT_SHA}}"
         git push 